### PR TITLE
More clear build & run instructions for beginners.

### PR DESCRIPTION
**Pull request by ghost**
Hello,

I had issues with the ZMQ connection (https://github.com/subreption/hackrf_sweeper/discussions/4). I kindly added the ZMQ curve key generation option and updated the README.md.

### CODE REVIEW

**Comment by sbrptdev2** [comment]
Hello @huzeyfe-erkek ,

Could you review https://github.com/subreption/hackrf_sweeper/commit/63a1c74b3dca9de8a0fd27598d4b08b6d8fac565 (merged earlier) and see if it addresses your issue)

Regarding the README.md: we do not wish to remove outputs as it is good practice to show the end-user what a successful build process looks like. For the shell command snippets you could use the shell syntax highlighting modifier.

Also: the server demo already performs key generation, look closely. If it fails to find the keys in the directory set by the user, they will be generated. The client should generate client keys, nothing else. It is also good practice to *not* automate key generation, as it puts the burden of learning how to manage the keyring on the user (and if he has no udnerstanding of the basic concept of key management then using CURVE probably is not going to help much in the long run).

**Comment by ghost** [comment]
Hello @sbrptdev2,

https://github.com/subreption/hackrf_sweeper/commit/63a1c74b3dca9de8a0fd27598d4b08b6d8fac565 works fine on my system when I start the client with `./demo/hackrf_sweeper_zmq2plot.py  -k ./test-keys -p ./test-keys/server.key
`

I understand my mistake. I didn't know that the server creates the key files. So, I copied-pasted the server.key file from the README.md, and since there was no server.key_secret file it didn't work. I'm sorry, I don't have much experience with CURVE and key management.

I think, this PR will not contribute. So, I am closing it.

**Comment by sbrptdev2** [comment]
Quite the contrary, we are more than happy to see the engagement and it is much appreciated. Generally, most people using the library (exponentially more so if it ever gets merged upstream) will not contribute back. This is how FOSS works most of the time. Even Jia Tan contributed more to xz than most of its user-base in the entirety of the project lifespan :>

Humor aside, if you feel like adjusting anything in the PR or have any enhancements or experiments to consider, please do come back.  I will be happy to help you maneuver through the code.

**Comment by sbrptdev2** [comment]
On that note, feel free to open a RFC/discussion issue on any enhancements. You seem interested in DSP. One of the things I did not have the time to complete was a Qt (PyQt is fine) demo with a viridis plot (waterfall). There are some implementation challenges with a streaming provider. There is also interest in a Rust crate for the library. Unit tests are also lacking (it's complicated to to implement these when you depend on device transfers I/O of very user specific data).

**Pull request closed without merging**
